<?php
/**
 * Sponsor click tracker for the Advanced Sponsor Manager.
 *
 * Generated by advanced_sponsor_manager_write_redirect_script(). Keep the real
 * logic in inc/plugins/advanced_sponsor_manager.php.
 */
define('IN_MYBB', 1);
require_once dirname(__FILE__).'/global.php';

advanced_sponsor_manager_handle_click();
