<?php
/**
 * ACP entry point for the Advanced Sponsor Manager.
 *
 * Generated by advanced_sponsor_manager_write_acp_module().
 */
if(!defined('IN_MYBB'))
{
        die('Direct initialization of this file is not allowed.');
}

require_once MYBB_ROOT.'inc/plugins/advanced_sponsor_manager.php';

advanced_sponsor_manager_acp_page();
