<?php
/**
 * ACP module shim for the Advanced Sponsor Manager.
 *
 * Generated by advanced_sponsor_manager_write_acp_module(). The real code lives
 * in inc/plugins/advanced_sponsor_manager.php so the plugin stays in one file.
 */
if(!defined('IN_MYBB'))
{
        die('Direct initialization of this file is not allowed.');
}

require_once MYBB_ROOT.'inc/plugins/advanced_sponsor_manager.php';

function advanced_sponsor_manager_meta()
{
        return advanced_sponsor_manager_acp_meta();
}

function advanced_sponsor_manager_action_handler($action)
{
        return advanced_sponsor_manager_acp_action_handler($action);
}

function advanced_sponsor_manager_admin_permissions()
{
        return advanced_sponsor_manager_acp_permissions();
}
